# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc1b1ee4d0f58b1ab56293bfd7c49a864a84b17c7ef68bd965b8bd3f4ca1efaa3e01c2cbb197d72139b9136aaa57b1b0d8ea801ebfef364cdb907ae88cef9e97

test:
  secret_key_base: 9056cf25a96199bf8eece89b97a66083536ea26ad682be2b5b70457b9270fc504ee7718b7143a192a66b889aca38a83d060f7b83dc80e91f682e5c8bd544e42a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
